### ISSUE TITLE
Result in Cell 39 does not match with code!

### ISSUE THREAD

**Issue by barzan-hayati** [Christophe-pere/Loss_function#1]
in cell where you want to draw `Exponential Loss` you do a mistake in drawing `y_true`

`y_true = [1 for _ in range(len(y))]`

at first `y_` does not exist and you mean `y_true`. But `y_true `would be a list with ones element: `[1,1,1, ...,1]`

after running this cell it generates this graph:

![image](https://user-images.githubusercontent.com/7418329/149203443-f266ed25-10b2-498d-880e-c4b7b2cba869.png)

while you bring this one 

![image](https://user-images.githubusercontent.com/7418329/149203632-0602cab5-8858-434a-99c6-2dea1189b597.png)

**Comment by barzan-hayati** [comment]
Also for cell number 307 I got different results for mean_square_Log_error:

My result: 

![image](https://user-images.githubusercontent.com/7418329/149209810-adfc7f77-98dc-486b-ae30-75866c3a0a49.png)

and your results:

![image](https://user-images.githubusercontent.com/7418329/149209864-8bfbd41a-8629-4bf0-8cda-1fb7d9d6856d.png)


As you can see here, trend of errors in right side are completely different.

**Comment by Christophe-pere** [comment]
Hi,
Thanks a lot for your issue. 
I corrected the different cells. I've seen some other bugs.
